# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/icons8-bitcoin-500.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("* {\n"
"background: #011526;\n"
"color: #F2F0D8; \n"
"font: 9pt \"Arial Rounded MT Bold\";\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 5px 15px;\n"
"    background-color: #100E19;\n"
"background: #1E3340\n"
"}\n"
"QPushButton::hover{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    padding: 5px 10px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #1E3340;\n"
"    background-color: #010626\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("#frame {\n"
"border-radius: 10px;\n"
"border: 1px solid #F2F0D8;\n"
"}\n"
"QFrame {\n"
"border: none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_4.setStyleSheet("border-image: url(\':/img/img/logo.jpeg\')")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setStyleSheet("font: 18pt \"Times New Roman\";\n"
"color: rgb(99, 99, 99);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("margin-left: 100px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("color: rgb(47, 50, 255);\n"
"color: #F2F0D8;\n"
"font: 8pt \"Arial Rounded MT Bold\";\n"
"font-size: 25px;\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("color: rgb(255, 8, 45);\n"
"font: 8pt \"Arial Rounded MT Bold\";\n"
"font-size: 18px;\n"
"\n"
"margin-left: 100px;\n"
"margin-bottom: 20px")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setStyleSheet("background-color: rgb(47, 130, 255);\n"
"margin-left: 215px;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buyLicenseBtn = QtWidgets.QPushButton(self.frame_4)
        self.buyLicenseBtn.setStyleSheet("color: #8C711F;\n"
"font: 8pt \"Arial Rounded MT Bold\";\n"
"font-size: 18px;\n"
"border: 1px solid black;\n"
"padding: 10px 5px;\n"
"border-radius: 10px;")
        self.buyLicenseBtn.setObjectName("buyLicenseBtn")
        self.horizontalLayout.addWidget(self.buyLicenseBtn)
        self.haveLicenseBtn = QtWidgets.QPushButton(self.frame_4)
        self.haveLicenseBtn.setStyleSheet("color: #8C711F;\n"
"font: 8pt \"Arial Rounded MT Bold\";\n"
"font-size: 18px;\n"
"\n"
"border: 1px solid black;\n"
"padding: 10px 5px;\n"
"border-radius: 10px;")
        self.haveLicenseBtn.setObjectName("haveLicenseBtn")
        self.horizontalLayout.addWidget(self.haveLicenseBtn)
        self.openSoftwareBtn = QtWidgets.QPushButton(self.frame_4)
        self.openSoftwareBtn.setStyleSheet("color: #8C711F;\n"
"font: 8pt \"Arial Rounded MT Bold\";\n"
"font-size: 18px;\n"
"\n"
"border: 1px solid black;\n"
"padding: 10px 5px;\n"
"border-radius: 10px;")
        self.openSoftwareBtn.setObjectName("openSoftwareBtn")
        self.horizontalLayout.addWidget(self.openSoftwareBtn)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Satoshi All Flasher - Welcome"))
        self.label_3.setText(_translate("MainWindow", "Satooshi Tools"))
        self.label.setText(_translate("MainWindow", "SATOOSHI TOOLS ALL FLASHER"))
        self.label_2.setText(_translate("MainWindow", "This software hasn\'t been activated yet.\n"
"Please buy wallet licence only from www.satoshitools.com.\n"
"Every licence is locked on computer MAC address and\n"
"IP cannot be used in another computer. This protects\n"
"our users from sacmmers."))
        self.buyLicenseBtn.setText(_translate("MainWindow", "Buy License Now"))
        self.haveLicenseBtn.setText(_translate("MainWindow", "I have License"))
        self.openSoftwareBtn.setText(_translate("MainWindow", "Open Software"))
import resources_rc
